print("🚀 DEPLOYMENT GUIDE - PRANAV7T/FAKE-NEWS-DETECTOR")
print("=" * 70)
print()

print("📋 YOUR REPOSITORY DETAILS:")
print("-" * 50)
print("• GitHub Repository: https://github.com/Pranav7T/fake-news-detector")
print("• Backend URL: https://fake-news-detector-api.onrender.com")
print("• Frontend URL: https://fake-news-detector.pranav7t.dev")
print("• Custom Domain: fake-news-detector.pranav7t.dev")
print()

print("🔧 STEP-BY-STEP DEPLOYMENT:")
print("-" * 50)
print("1️⃣  BACKEND DEPLOYMENT (RENDER):")
print("-" * 30)
print("a) Go to https://render.com")
print("b) Sign up/login with GitHub")
print("c) Click 'New' → 'Web Service'")
print("d) Connect: https://github.com/Pranav7T/fake-news-detector")
print("e) Configure:")
print("   • Name: fake-news-detector-api")
print("   • Environment: Python 3")
print("   • Region: Choose nearest")
print("   • Branch: main")
print("   • Root Directory: .")
print("   • Build Command: pip install -r requirements-deploy.txt")
print("   • Start Command: gunicorn --bind 0.0.0.0:$PORT app:app")
print("   • Instance Type: Free")
print()
print("f) Add Environment Variables:")
print("   • PYTHON_VERSION: 3.11.5")
print("   • FLASK_ENV: production")
print()
print("g) Click 'Create Web Service'")
print("h) Wait for deployment (2-3 minutes)")
print()

print("2️⃣  GET RENDER API KEY:")
print("-" * 30)
print("a) Go to Render Dashboard")
print("b) Click your profile → Account Settings")
print("c) Go to 'API Keys' tab")
print("d) Click 'Create API Key'")
print("e) Name it: 'fake-news-detector-key'")
print("f) Copy the API key")
print()
print("g) Get Service ID:")
print("   • Go to your service dashboard")
print("   • Service ID is in the URL: /srv/srv-xxxxxxx")
print("   • Copy the srv-xxxxxxx part")
print()

print("3️⃣  SETUP GITHUB SECRETS:")
print("-" * 30)
print("a) Go to: https://github.com/Pranav7T/fake-news-detector/settings/secrets")
print("b) Click 'New repository secret'")
print("c) Add:")
print("   • Name: RENDER_API_KEY")
print("   • Value: [paste your Render API key]")
print("d) Click 'Add secret'")
print()
print("e) Add another secret:")
print("   • Name: RENDER_SERVICE_ID") 
print("   • Value: [paste your service ID like srv-xxxxxxx]")
print("f) Click 'Add secret'")
print()

print("4️⃣  ENABLE GITHUB PAGES:")
print("-" * 30)
print("a) Go to: https://github.com/Pranav7T/fake-news-detector/settings/pages")
print("b) Source: Deploy from a branch")
print("c) Branch: main")
print("d) Folder: /root")
print("e) Click 'Save'")
print()

print("5️⃣  SETUP CUSTOM DOMAIN (OPTIONAL):")
print("-" * 30)
print("a) Go to GitHub Pages settings")
print("b) Custom domain: fake-news-detector.pranav7t.dev")
print("c) Add DNS records at your domain provider:")
print("   • Type: CNAME")
print("   • Name: fake-news-detector")
print("   • Value: Pranav7T.github.io")
print()

print("6️⃣  DEPLOY!")
print("-" * 30)
print("a) Commit and push changes:")
print("   git add .")
print("   git commit -m 'Ready for deployment'")
print("   git push origin main")
print()
print("b) GitHub Actions will automatically:")
print("   • Run tests")
print("   • Deploy backend to Render")
print("   • Deploy frontend to GitHub Pages")
print()

print("🔍 VERIFICATION:")
print("-" * 50)
print("After deployment, test these URLs:")
print("• Backend Health: https://fake-news-detector-api.onrender.com/health")
print("• Backend API: https://fake-news-detector-api.onrender.com/")
print("• Frontend: https://fake-news-detector.pranav7t.dev")
print("• Custom Domain: https://fake-news-detector.pranav7t.dev")
print()

print("🧪 TESTING COMMANDS:")
print("-" * 50)
print("# Test backend health")
print("curl https://fake-news-detector-api.onrender.com/health")
print()
print("# Test API endpoint")
print("curl -X POST https://fake-news-detector-api.onrender.com/predict \\")
print("  -H 'Content-Type: application/json' \\")
print("  -d '{\"text\": \"Test news article\"}'")
print()
print("# Test frontend in browser")
print("# Visit: https://fake-news-detector.pranav7t.dev")
print()

print("📱 MOBILE TESTING:")
print("-" * 50)
print("• Test on mobile browsers")
print("• Check responsive design")
print("• Verify all features work")
print("• Test loading animations")
print()

print("🔧 TROUBLESHOOTING:")
print("-" * 50)
print("If deployment fails:")
print()
print("1. Backend Issues:")
print("   • Check Render build logs")
print("   • Verify requirements-deploy.txt")
print("   • Check model files exist")
print("   • Verify app.py syntax")
print()
print("2. Frontend Issues:")
print("   • Check GitHub Actions logs")
print("   • Verify package.json scripts")
print("   • Check build process")
print("   • Verify GitHub Pages enabled")
print()
print("3. CORS Issues:")
print("   • Check frontend API URL")
print("   • Verify CORS configuration")
print("   • Check environment variables")
print()

print("📊 MONITORING:")
print("-" * 50)
print("• Render Dashboard: https://dashboard.render.com")
print("• GitHub Actions: https://github.com/Pranav7T/fake-news-detector/actions")
print("• GitHub Pages: https://github.com/Pranav7T/fake-news-detector/pages")
print()

print("🎉 SUCCESS CRITERIA:")
print("-" * 50)
print("✅ Backend responding at https://fake-news-detector-api.onrender.com")
print("✅ Frontend loading at https://fake-news-detector.pranav7t.dev")
print("✅ All analysis modes working")
print("✅ Source verification functional")
print("✅ Loading animations displaying")
print("✅ Mobile responsive design")
print("✅ CI/CD pipeline active")
print()

print("🚀 YOUR AI FAKE NEWS DETECTOR WILL BE LIVE AT:")
print("-" * 50)
print("🌐 Frontend: https://fake-news-detector.pranav7t.dev")
print("⚙️  Backend: https://fake-news-detector-api.onrender.com")
print("📱 Mobile: https://fake-news-detector.pranav7t.dev (responsive)")
print()

print("✨ READY TO IMPRESS AT YOUR EXHIBITION! ✨")
print()
print("📞 NEED HELP?")
print("• Check deployment logs")
print("• Review this guide")
print("• Test all endpoints")
print("• Verify mobile compatibility")
